name: Actions from issues

on:
  issues:
    types:
      - labeled

jobs:
  new-olym-post:
    if: github.event.label.name == 'ğŸ…newolympost'
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      - name: Use Volta
        uses: volta-cli/action@v1

      - name: Install dependencies
        run: yarn install

      - name: Create new post and set path as env var
        run: yarn run --silent util:olym new "${{ github.event.issue.title }}" | { read v ;echo -e POST_PATH="$v"; } >> $GITHUB_ENV
        shell: bash

      - name: Set problem code as env var
        run: yarn run --silent util:olym code "${{ github.event.issue.title }}" | { read v ;echo -e PROB_CODE="$v"; } >> $GITHUB_ENV
        shell: bash

      - name: Set branch name as env var
        run: echo 'BRANCH_NAME=article/${{ github.event.issue.number }}-${{ env.PROB_CODE }}' >> $GITHUB_ENV

      - name: Create new branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git switch -c ${{ env.BRANCH_NAME }}
          git push -u origin ${{ env.BRANCH_NAME }}

      - name: Add and Commit
        uses: EndBug/add-and-commit@v7
        with:
          branch: ${{ env.BRANCH_NAME }}
          message: add ${{ env.PROB_CODE }} post
          add: ${{ env.POST_PATH }}

      - name: Set env var for comment
        run: |
          echo ${{ env.BRANCH_NAME }} | sed -e "s/\//-/g" | awk '{print "SUBDOMAIN="$1}' >> $GITHUB_ENV
          echo ${{ env.POST_PATH }} | sed -e "s/src\///g" | sed -e "s/index\.md//g" | awk '{print "WEB_PATH="$1}' >> $GITHUB_ENV

      - name: Add comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            ## ğŸš€ New Post

            | | Links |
            | :-- | :-- |
            | ğŸªµ Branch | [`${{ env.BRANCH_NAME }}`](https://github.com/hulinguistics/huling/tree/${{ env.BRANCH_NAME }}) |
            | âœ Post | [`${{ env.POST_PATH }}`](https://github.com/hulinguistics/huling/blob/${{ env.BRANCH_NAME }}/${{ env.POST_PATH }}) ([Edit on Web](https://github.com/hulinguistics/huling/edit/${{ env.BRANCH_NAME }}/${{ env.POST_PATH }})) |
            | â˜ Preview | [here](https://${{ env.SUBDOMAIN }}.huling-dxj.pages.dev/${{ env.WEB_PATH }}) (please wait a few mins) |
