name: Actions from issues

on:
  issues:
    types:
      - labeled

jobs:
  new-lang-post:
    if: github.event.label.name == 'ğŸƒnewlangpost'
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      - name: Use Volta
        uses: volta-cli/action@v1

      - name: Install dependencies
        run: yarn install

      - name: Create new post and set path as env var
        run: echo 'POST_PATH=$(yarn run --silent util:lang new "${{ github.event.issue.title }}")' >> $GITHUB_ENV

      - name: Set iso code as env var
        run: echo 'ISO_CODE=$(yarn run --silent util:lang iso "${{ github.event.issue.title }}")' >> $GITHUB_ENV

      - name: Set branch name as env var
        run: echo 'BRANCH_NAME=article/${{ github.event.issue.number }}_${{ env.ISO_CODE }}' >> $GITHUB_ENV

      - name: Create new branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git switch -c ${{ env.BRANCH_NAME }}
          git push -u origin ${{ env.BRANCH_NAME }}

      - name: Add and Commit
        uses: EndBug/add-and-commit@v7
        with:
          branch: ${{ env.BRANCH_NAME }}
          message: add ${{ env.ISO_CODE }}
          add: ${{ env.POST_PATH }}

      - name: Set env var for comment
        run: |
          echo 'SUBDOMAIN=${${{ env.BRANCH_NAME }}//\//-}' >> $GITHUB_ENV
          echo 'WEB_PATH=${${${{ env.POST_PATH }}#src/}%index.md}' >> $GITHUB_ENV

      - name: Add comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            ## ğŸš€ New Post

            | | Links |
            | :-- | :-- |
            | ğŸªµ Branch | [`${{ env.BRANCH_NAME }}`](https://github.com/hulinguistics/huling/tree/${{ env.BRANCH_NAME }}) |
            | âœ Post | [`${{ env.POST_PATH }}`](https://github.com/hulinguistics/huling/blob/${{ env.BRANCH_NAME }}/${{ env.POST_PATH }}) ([edit](https://github.com/hulinguistics/huling/edit/${{ env.BRANCH_NAME }}/${{ env.POST_PATH }})) |
            | â˜ Preview | [here](https://${{ env.SUBDOMAIN }}.huling-dev.pages.dev/${{ env.WEB_PATH }}) |
